name: Nightly Turtle Scanner

on:
  workflow_dispatch:   # manual run (button click)
  schedule:
    - cron: "0 2 * * *"   # runs daily at 2:00 UTC

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Turtle script
        run: |
          python TotalNarrow.py \
            --system 1 \
            --allow-shorts 1 \
            --top 300 \
            --save entries_tomorrow.csv \
            --emit-checklist 1

      - name: Upload results (CSV + checklist)
        uses: actions/upload-artifact@v4
        with:
          name: turtle-output
          path: |
            *.csv
            *.txt
