name: Run Python Script (with libs)

on:
  workflow_dispatch:  # manual "Run workflow" button
  # Optional schedule (remove if you don't want it)
  # schedule:
  #   - cron: "0 3,13 * * *"  # daily 3:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python script.py
